+PDF prev
kregfile/kregfile pull request #59
Opened 2021-07-22 22:00 UTC by voroneril

2021-07-22 22:15 UTC, RealDolos requested changes
Things must work in node-14-lts at the very least.
node-12-lts and 16 a plus.

2021-07-22 22:15 UTC, RealDolos commented on package.json
> +    "gm": "^1.23.1",
Make this an optional dependency please. I really do not like gm/imagemagick much. And it's a huge dependency.
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#optionaldependencies

2021-07-22 22:15 UTC, RealDolos commented on lib/meta.js
> +const gm = require('gm')
if you make this optional you have to guard with try-catch here

2021-07-22 22:15 UTC, RealDolos commented on lib/meta.js
> +      EXIFTOOL, "-b", "-Picture", `${p.dir}/${p.base}`
nope, this was correct, except your jailing is not working. Turn off jail in your config, and do not change this

2021-07-22 22:15 UTC, RealDolos commented on lib/meta.js
> +  const base = await sharp(storage.full).
this breaks on later sharps that this repo uses. Do not change it like this

2021-07-22 22:15 UTC, RealDolos commented on lib/meta.js
> +  console.log('storage.meta.type', storage.meta.type);
make this a console.debug

2021-07-22 22:15 UTC, RealDolos commented on lib/meta.js
> +  if (storage.meta.type == "PDF" ||storage.meta.type == "pdf") {
Optional check ;)

2021-07-22 22:15 UTC, RealDolos commented on lib/meta.js
> +        limitInputPixels(PIXEL_LIMIT).
Same issue here that later versions of sharp does not support it like this...

2021-07-22 22:15 UTC, RealDolos commented on lib/meta.js
> +        FILETOOL, "-d", "--mime-type", `${p.dir}/${p.base}`
Do not change this either

2021-07-23 11:17 UTC, voroneril commented
All should be now fixed

2021-07-23 11:34 UTC, RealDolos approved these changes

2021-07-23 11:57 UTC, closed without merging