Docker Support
kregfile/kregfile pull request #91
Opened 2023-03-10 21:51 UTC by hggggggggggggggg

Hello, sirs. I have added docker support to kregfile. Kindly pull the commit to master.

2023-03-10 22:01 UTC, RealDolos requested changes
Sirs, you have many mistakes, sirs

2023-03-10 22:01 UTC, RealDolos commented on docker-compose.yml
> +        source: ./.config.json
>file not found

2023-03-10 22:33 UTC, hggggggggggggggg commented
Hello, sirs. I do not know what you mean. I have reopened the pull request.

2023-03-11 04:01 UTC, hggggggggggggggg commented
I made a change to the Dockerfile to simplify the redis docker-compose. I also corrected the comments in the docker-compose.

2023-03-14 03:32 UTC, closed without merging